mod Later.TestImpureLazyList {
    use Later.ImpureLazyList
    use Later.ImpureLazyList.filter
    use Later.ImpureLazyList.head
    use Later.ImpureLazyList.map
    use Later.ImpureLazyList.tail
    use Later.ImpureLazyList.take
    use Later.ImpureLazyList.uncons
    use Later.ImpureLazyList.toIterator
    use Later.ImpureLazyList.fromIterator
    use Later.ImpureLazyList.toList
    use Later.ImpureLazyList.fromList



}